USE TestDB
GO


DROP TABLE IF EXISTS dbo.stg_Competitions
GO


CREATE TABLE dbo.stg_Competitions
(
    id  INT           NOT NULL IDENTITY,

    F1  NVARCHAR(255) NULL,
	F2  NVARCHAR(255) NULL,
	F3  NVARCHAR(255) NULL,
	F4  NVARCHAR(255) NULL,
	F5  NVARCHAR(255) NULL,
	F6  NVARCHAR(255) NULL,
	F7  NVARCHAR(255) NULL,
	F8  NVARCHAR(255) NULL,
	F9  NVARCHAR(255) NULL,

	CONSTRAINT PK_stg_Competitions PRIMARY KEY
	(
	    id
	)
)
GO